import { Inter } from 'next/font/google';
import Menu from '../../components/Menu';
import './globals.css';
import styles from './layout.module.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={styles.layout}>
        <Menu />
        {children}
      </body>
    </html>
  );
}
